spring:
  application:
    name: microservice-eureka-server
  profiles: peer1 #申明环境，启动时可以指定不同的环境进行启动

server:
  port: 8761  #服务端口号

eureka:
  instance:
    hostname: eureka-server-peer1 #实例名称
    lease-renewal-interval-in-seconds: 5 # 心跳时间，即服务续约间隔时间（缺省30s）
    lease-expiration-duration-in-seconds: 15 # 发呆时间，即服务续约到期时间（缺省为90s）

  server:
    enable-self-preservation: false       # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 1000   # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
  client:
    register-with-eureka: false # 代表不向注册中心注册自己
    fetch-registry: false # 不需要检索服务
    serviceUrl:
      defaultZone: http://eureka-server-peer2:8762/eureka/,http://eureka-server-peer3:8763/eureka/